FROM node:16-alpine as build

WORKDIR /usr/src/app

COPY package*.json ./

COPY . .

RUN npm run build && apk add tzdata

FROM node:16-alpine as production


WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY . .

COPY --from=build /usr/src/app/dist ./dist

CMD ["npm", "run", "start:debug"] 